import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Navbar } from "./components/Navbar";
import clsx from "clsx";
import { ClerkProvider } from "@clerk/nextjs/app-beta";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "E-Commerce Next ",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (

    <ClerkProvider>
      <html lang="en">
        <body className={clsx(inter.className, "bg-slate-400")}>

          <Navbar />

          <main className=" p-16 h-screen">{children}</main>

        </body>
      </html>
    </ClerkProvider>
  );
}
